export interface IBranchMaster {
    id: number,
    name: string,
    collegeId: number,
    collegeName: string,
    programMasterId: number,
    programName: string,
    studyMasterId: number,
    studyName: string,
    departmentId: number,
    departmentName: string,
    abbreviation: string,
    branchPrefix: string,
    dateOfIntrodution: Date,
    mediumOfInstruction: string,
    affiliationStatus: string,
    accreditationstatus: string,
    code: string,
    isActive: boolean,
    createdBy?: string,
    createdDate?: Date,
    updatedBy?: string,
    updatedDate?: Date
}