export * from "./IBranchMaster";
export * from "./ICollegeMaster";
export * from "./ISeatTypeMaster";
export * from "./IStreamMaster";
export * from "./IExamTypeMaster";
export * from "./IFeeHeadTypeMaster";
export * from "./IFeeHeadMaster";
export * from "./ICourseTypeMaster";
export * from "./IProgramYearMaster";
export * from "./IBankMaster";
export * from "./ISyllabusPatternMaster";
export * from "./IAllotmentCategoryMaster"
export * from "./IModeOfAdmissionMaster";
export * from "./IProgramDetailMaster";
export * from "./ISMSTemplateMaster"
export * from "./ISemesterDetailsMaster";
export * from "./IApplicationStatusMaster";
export * from "./IApplicationRejectReasons";