// export * from "./IAnnualIncomeMaster";
export * from "./IAppointmentTypeMaster";
export * from "./IBloodGroupMaster";
// export * from "./IBoardMaster";
// export * from "./ICandidatureTypeMaster";
// export * from "./ICasteCategoryMaster";
export * from "./ICasteMaster";
// export * from "./ICommonMaster";
// export * from "./ICommonMasterDetails";
export * from "./ICommonSubjectMaster";
export * from "./ICountryMaster";
export * from "./ICourseCategoryMaster";
export * from "./IDistrictMaster";
export * from "./IDomicileMaster";
export * from "./IEmployeeTypeMaster";
export * from "./IHandicapType";
// export * from "./IMinorityDetailsMaster";
export * from "./IMinorityMaster";
export * from "./IMotherTongueMaster";
export * from "./IRelationMaster";
export * from "./IReligionMaster";
// export * from "./ISemesterMaster";
// export * from "./ISMTPConfigMaster";
export * from "./IStateMaster";
//export * from "./ISubCasteMaster";
export * from "./ITalukaMaster";
export * from "./ITimeSlotMaster";
export * from "./ISemesterMaster";
