export interface IOfflineStudentDetails {
    isActive: boolean
    createdBy: number
    createdDate: string
    updatedBy: number
    updatedDate: string
    studentAdmissionId: number
    userId: number
    collegeId: number
    academicYearId: number
    domicileId: number
    religionId: number
    studentCategoryId: number
    casteId: number
    subCasteId: number
    minorityId: number
    minorityDetailsId: number
    title: string
    lastName: string
    firstName: string
    middleName: string
    nameAsMarkSheet: string
    admisssionDate: string
    gender: string
    dateOfBirth: string
    placeOfBirth: number
    maritalStatus: string
    bloodGroup: number
    childNoInFamily: number
    noOfSiblings: number
    motherTounge: string
    nationality: string
    studentMailId: string
    aadharNo: string
    panNo: string
    voterId: string
    mobileNo: string
    whatsAppMobileNo: string
    physicallyChallaged: boolean
    disabilityType: number
    isMinority: boolean
    emergencyContactNo: string
    languageKnown: string
    passportNo: string
    isDefenceParent: boolean
    defenceType: string
    region: string
    drivingLicenceNo: string
    passportExpiryDate: string
    annualIncomeId: number
  }
  